[connections.postgresql]
# dialect = "postgresql"
host = "150.230.252.85"
port = "5432"
database = "edrugs"
user = "devcell"
password = "devcell"

[postgresql]
host = "150.230.252.85"
port = "5432"
database = "edrugs"
user = "devcell"
password = "devcell"